<?php 
global $game_list_db_version;
$game_list_db_version = "1.2";

function game_list_install () {
	global $wpdb;
	global $game_list_db_version;

	$table_name = $wpdb->prefix . "game_list";
	if($wpdb->get_var("show tables like '$table_name'") != $table_name) {
      
		$sql_create = "CREATE TABLE " . $table_name . " (
			id INT(11)  NOT NULL,
			gametype varchar(45) NOT NULL,
			gamename varchar(45) NOT NULL,
			gamename_nice varchar(45) DEFAULT 'yes' NOT NULL,
			noiq varchar(45) DEFAULT 'yes' NOT NULL
		);";

		$sql_insert = "INSERT INTO " . $table_name . " (id,gametype,gamename,gamename_nice,noiq) 
		VALUES 
		(1,'Baccarat','baccarat2','Baccarat 2','yes'),
		(2,'Blackjack','blackjack2-3h','Blackjack 2-3h','yes'),
		(3,'Blackjack','blackjackdblex','Blackjack Double Xposure','yes'),
		(4,'Blackjack','blackjackflash','Blackjack Flash','yes'),
		(5,'Blackjack','blackjackonedk','Blackjack Single Deck','yes'),
		(6,'Blackjack','blackjackpntn','Blackjack Pontoon','yes'),
		(7,'Slots','beetle','Beetle','yes'),
		(8,'Poker','casinoholdem','Casino Holdem','yes'),
		(9,'Poker','cstud2','Caribbean Stud','yes'),
		(10,'Poker','cstudflash','Caribbean Stud Flash','yes'),
		(11,'Card Games','hilo2-3c','Hi-Lo Switch','yes'),
		(12,'Baccarat','hrbaccarat2','Baccarat 2 HR','yes'),
		(13,'Blackjack','hrblackjack2-3h','Blackjack 2-3h HR','yes'),
		(14,'Blackjack','hrblackjackdblex','Blackjack Double Xposure HR','yes'),
		(15,'Blackjack','hrblackjackonedk','Blackjack Single Deck HR','yes'),
		(16,'Blackjack','hrblackjackpntn','Blackjack Pontoon HR','yes'),
		(17,'Poker','hrcstud2','Caribbean Stud HR','yes'),
		(18,'Card Games','hrhilo2-3c','Hi-Lo Swich HR','yes'),
		(19,'Card Games','hrletitride2','Let It Ride HR','yes'),
		(20,'Poker','hroasispoker','Oasis Poker HR','yes'),
		(21,'Card Games','hrpuntobanco','Punto Banco HR','yes'),
		(22,'Poker','hrtreypoker-1h','Trey Poker One Handed HR','yes'),
		(23,'Poker','hrtxsholdem','Texas Holdem HR','yes'),
		(24,'Card Games','letitride2','Let It Ride','yes'),
		(25,'Baccarat','lrbaccarat2','Baccarat 2 LR','yes'),
		(26,'Blackjack','lrblackjack2-3h','Blackjack 2-3h LR','yes'),
		(27,'Blackjack','lrblackjackdblex','Blackjack Double Xposure LR','yes'),
		(28,'Blackjack','lrblackjackonedk','Blackjack Single Deck LR','yes'),
		(29,'Blackjack','lrblackjackpntn','Blackjack Pontoon LR','yes'),
		(30,'Poker','lrcstud2','Caribbean Stud LR','yes'),
		(31,'Card Games','lrhilo2-3c','Hi-Lo Swich LR','yes'),
		(32,'Card Games','lrletitride2','Let It Ride LR','yes'),
		(33,'Poker','lroasispoker','Oasis Poker LR','yes'),
		(34,'Card Games','lrpuntobanco','Punto Banco LR','yes'),
		(35,'Roulette','lrroulette2adv','Roulette LR','yes'),
		(36,'Roulette','lrroulette2french','French Roulette LR','yes'),
		(37,'Poker','lrtreypoker-1h','Trey Poker LR','yes'),
		(38,'Poker','lrtxsholdem','Texas Holdem LR','yes'),
		(39,'Poker','oasispoker','Oasis Poker','yes'),
		(40,'Card Games','puntobanco','Punto Banco','yes'),
		(41,'Card Games','reddog','Red Dog','yes'),
		(42,'Roulette','roulette2adv','Roulette','yes'),
		(43,'Roulette','roulette2french','French Roulette','yes'),
		(44,'Poker','treypoker-1h','Trey Poker','yes'),
		(45,'Slots','jackpot6k','Jackpot 6K','yes'),
		(46,'Slots','luckyeight','Lucky Eight','yes'),
		(47,'Slots','luckyeightlove','Lucky Eight Love','yes'),
		(48,'Slots','luckyeightsafari','Lucky Eight Safari','yes'),
		(49,'Slots','megajoker','Megajoker','yes'),
		(50,'Slots','piratesgold2','Pirates Gold','yes'),
		(51,'Video Slots','bloodsuckers','Blood Suckers','yes'),
		(52,'Video Slots','champion','Champion','yes'),
		(53,'Video Slots','crusaders','Crusaders','yes'),
		(54,'Video Slots','deadoralive','Dead or Alive','yes'),
		(55,'Video Slots','devil','Devil','yes'),
		(56,'Video Slots','diamonddogs','Diamond Dogs','yes'),
		(57,'Video Slots','eldorado','Eldorado','yes'),
		(58,'Video Slots','excalibur','Excalibur','yes'),
		(59,'Video Slots','fishyfortune','Fishy Fortune','yes'),
		(60,'Video Slots','fortuneteller','Fortuneteller','yes'),
		(61,'Video Slots','frog','Frog','yes'),
		(62,'Video Slots','geisha','Geisha','yes'),
		(63,'Video Slots','ghostpirates','Ghost Pirates','yes'),
		(64,'Video Slots','horus','Horus','yes'),
		(65,'Video Slots','hotcity','Hot City','yes'),
		(66,'Video Slots','ice','Ice','yes'),
		(67,'Video Slots','junglegames','Jungle Games','yes'),
		(68,'Video Slots','krakow','Krakow','yes'),
		(69,'Video Slots','mansion','Mansion','yes'),
		(70,'Video Slots','pacific','Pacific','yes'),
		(71,'Video Slots','pandorasbox','Pandoras Box','yes'),
		(72,'Video Slots','piggyriches','Piggy Riches','yes'),
		(73,'Video Slots','reelsteal','Reel Steal','yes'),
		(74,'Video Slots','relicraiders','Relic Raiders','yes'),
		(75,'Video Slots','retro-funky70','Retro Funky 70','yes'),
		(76,'Video Slots','retro-groovy60','Retro Groovy 60','yes'),
		(77,'Video Slots','retro-super80','Retro Super 80','yes'),
		(78,'Video Slots','secretcode','Secret Code','yes'),
		(79,'Video Slots','thrillspin','Thrill Spin','yes'),
		(80,'Video Slots','tiki','Tiki','yes'),
		(81,'Video Slots','viking','Viking','yes'),
		(82,'Video Slots','voodoo','Voodoo','yes'),
		(83,'Video Slots','wildwitches','Wild Witches','yes'),
		(84,'Video Slots','wizards','Wizards','yes'),
		(85,'Video Poker','allamerican1','All American 1','yes'),
		(86,'Video Poker','allamerican10','All American 10','yes'),
		(87,'Video Poker','allamerican100','All American 100','yes'),
		(88,'Video Poker','allamerican25','All American 25','yes'),
		(89,'Video Poker','allamerican5','All American 5','yes'),
		(90,'Video Poker','allamerican50','All American 50','yes'),
		(91,'Video Poker','deuceswild1','Deuces Wild 1','yes'),
		(92,'Video Poker','deuceswild10','Deuces Wild 10','yes'),
		(93,'Video Poker','deuceswild100','Deuces Wild 100','yes'),
		(94,'Video Poker','deuceswild25','Deuces Wild 25','yes'),
		(95,'Video Poker','deuceswild5','Deuces Wild 5','yes'),
		(96,'Video Poker','deuceswild50','Deuces Wild 50','yes'),
		(97,'Video Poker','jacksorbetter1','Jacks or Better 1','yes'),
		(98,'Video Poker','jacksorbetter10','Jacks or Better 10','yes'),
		(99,'Video Poker','jacksorbetter100','Jacks or Better 100','yes'),
		(100,'Video Poker','jacksorbetter25','Jacks or Better 25','yes'),
		(101,'Video Poker','jacksorbetter5','Jacks or Better 5','yes'),
		(102,'Video Poker','jacksorbetter50','Jacks or Better 50','yes'),
		(103,'Video Poker','jokerwild1','Jokers Wild 1','yes'),
		(104,'Video Poker','jokerwild10','Jokers Wild 10','yes'),
		(105,'Video Poker','jokerwild100','Jokers Wild 100','yes'),
		(106,'Video Poker','jokerwild25','Jokers Wild 25','yes'),
		(107,'Video Poker','jokerwild5','Jokers Wild 5','yes'),
		(108,'Video Poker','jokerwild50','Jokers Wild 50','yes'),
		(109,'Other Games','bingo','Bingo','yes'),
		(110,'Lottery','fortuna','Fortuna','yes'),
		(111,'Other Games','horserace','Horse Race','yes'),
		(112,'Other Games','kenobnjp','Keno','yes'),
		(113,'Other Games','zodiac','Zodiac','yes'),
		(114,'Blackjack','blackjackmini','Blackjack mini','yes'),
		(115,'Video Slots','cashbomb','Cash Bomb mini','yes'),
		(116,'Other Games','footballcupmini','Football Cup mini','yes'),
		(117,'Blackjack','hrblackjackmini','Blackjack mini HR','yes'),
		(118,'Blackjack','lrblackjackmini','Blackjack mini LR','yes'),
		(119,'Roulette','lrroulettemini','Roulette mini LR','yes'),
		(120,'Lottery','minispellmini','Minispell mini','yes'),
		(121,'Roulette','roulettemini','Roulette mini','yes'),
		(122,'Video Slots','soccerslammini','Soccerslam mini','yes'),
		(123,'Lottery','tribblemini','Tribble mini','yes'),
		(124,'Video Slots','vault','Vault','yes'),
		(125,'Lottery','acescratch','Aces Scratch','yes'),
		(126,'Lottery','halloffame','Hall of Fame','yes'),
		(127,'Lottery','hrscratchticketjp','Scratch Ticket HR','yes'),
		(128,'Lottery','knockout','Knock Out','yes'),
		(129,'Lottery','lrscratchticket','Scratch Ticket LR','yes'),
		(130,'Lottery','luckydouble','Lucky Double','yes'),
		(131,'Lottery','maxwin','Max Win','yes'),
		(132,'Lottery','scratchticket','Scratch Ticket','yes'),
		(133,'Lottery','sevengoldscratch','Seven Gold Scratch','yes'),
		(134,'Lottery','tribble','Tribble','yes'),
		(135,'Poker','poker-qlaff','Texas Holdem Poker','no')
		";

		require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
		dbDelta($sql_create);
		dbDelta($sql_insert);
 
		add_option("game_list_db_version", $game_list_db_version);
	}
}
register_activation_hook(ABSPATH . 'wp-content/plugins/qlaff/qlaff-toplist.php','game_list_install');
?>
